### PR TITLE
build(deps): update dependency ng2-pdf-viewer to v5.3.3

### PR DESCRIPTION
**Pull request by JoostK**
Replaces #219 by updating both `ng2-pdf-viewer` and `pdfjs-dist`, avoiding a problem where two instances of `pdfjs-dist` were installed.

### CODE REVIEW

**Comment by mgechev** [comment]
@JoostK can we fix this upstream? I see that `ng2-pdf-viewer` already has `pdfjs-dist` as a dependency.

**Comment by JoostK** [comment]
@mgechev We have `pdfjs-dist` in our `package.json` as it is also a peer dep of `@alfresco/adf-core`. However, looking at the `package.json` of `ng2-pdf-viewer` they have `pdfjs-dist` both as dep *and* peer dep, which makes no sense. I'll open a PR with them to remove the dep and only have the peer dep remain.

I am not really sure how we ended up with two versions of `pdfjs-dist` to be hones, as our version constraint would perfectly allow for just 2.2.228 to be installed by itself, without 2.1.266.

**Comment by mgechev** [comment]
Thanks for the clarification! I'd suggest to open an issue first since moving the library as a peer dependency will change the install process for the developers using the package.

**Comment by JoostK** [comment]
@mgechev Yes I realized that. I was about to write a PR description with **BREAKING CHANGE** in large text, but going with an issue first seems like a good idea :-)

**Pull request merged**
