### PR TITLE
Ci fixes

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

**Comment by alan-agius4** [comment]
I think that eventually we should remove known broken from CI or at least split them
so that;

We can have a proper red and green CI and if there is a regression we can easily spot it since CI will become red.

Thus, I would suggest that we have 2 CI setups.

- Build  (This will build all the packages that are known to work)
- Build Unknown Broken - CI for known broken packages, this can be an optional one, and can be good to know if any package went from being unsupported to supported.

**Comment by mgechev** [comment]
@alan-agius4 ready for review?

The suggestion makes sense. I should be able to look into this today.

**Comment by alan-agius4** [comment]
Not really, I am still trying to generate the lock files. It's taking forever.

**Comment by alan-agius4** [comment]
@mgechev see individual commits for more context. Would be great if you can enable circle on PRs to confirm it's okay.

I still didn't manage to successfully generate all lock files and for the time being i revert back to using `npm i` instead of `npm ci`.

I am going to call it a day, maybe tomorrow ill be more lucky with the lock files, if you want to give it a shot yourself, you can use the update deps command.

**Pull request merged**
