### PR TITLE
infra: change infra to angular cli mono repo

### PR DESCRIPTION
**Pull request by alan-agius4**
With this change we change the infrastructure of the packages testing to use Angular CLI mono repo. 

All packages are installed at root level which helps us in several ways

1. Reduce dependency installation time 
2. Fixes renovate timeouts since it has only a single package.json to maintain
3. NGCC doesn't need to run multiple times on common modules such as `@angular/core`, `@angular/common` etc.

The disadvantage of this is that we cannot run builds in parallel and hence, the build pool has been reduced to 1, this is because NGCC cannot run on the same `node_modules` from 2 different processes as it will result race conditions and that packages are not sandbox, which means that common dependencies are shared and might cause conflict of mismatches versions.

### CODE REVIEW

**Comment by alan-agius4** [comment]
FYI: CI times have increased, to 1hr for each run. Unfortunately we cannot shard the builds on free Circle CI.

**Comment by JoostK** [comment]
I much prefer the single `node_modules` over faster CI times, as I was unable to run everything on my laptop before due to my SSD running out of space :) And parallelization of ngcc itself is in the works ;)

**Comment by JoostK** [comment]
And btw, the most recent run on CCI was just 30 minutes, which is roughly equal to what it was before. It has been fluctuating between 30 minutes and one hour for a while, so this PR doesn't seem to have that much of a negative impact.

**Comment by alan-agius4** [comment]
@rarkins, can you kindly check if we are hitting timeouts after this change? Thanks.

**Comment by rarkins** [comment]
@alan-agius4 I'll take a look later today or tomorrow.

BTW other options I had thought about suggesting were either Yarn Workspaces or pnpm. Both result in less modules installed and a single lock file. I'm not sure if either would result in a "best of both worlds" that satisfies everyone above though.

**Comment by alan-agius4** [comment]
With the new changes, we have now a single package.json and lock file. So I am hoping that it should help with the timeouts. Though I didn't see any PR from renovate even though we have several dependency updates ticked in the master issues.

Yarn is an option, though now I am not sure how beneficial that would be since we have 1 package.json. PNPM is not on the table at the moment as the CLI/NGCC don't fully support it yet.

Thanks.

**Pull request merged**
