### PR TITLE
ci: use npm ci instead of npm i

### PR DESCRIPTION
**Pull request by alan-agius4**
build: update all lock files

### CODE REVIEW

**Comment by alan-agius4** [comment]
Need to check why we have so many failures 
```
Total: 173, Success: 40, Failed: 133
```

Most of the failures are due to `ERROR in Cannot read property 'flags' of undefined `

**Comment by alan-agius4** [comment]
Locks like the errors were due to incorrect lock files

**Comment by alan-agius4** [comment]
`npm run build` went down from 49 to 32mins

**Comment by mgechev** [comment]
@alan-agius4 do we still get the 133 failures?

**Comment by alan-agius4** [comment]
No, those failures were due to lock file issues.

**Comment by alan-agius4** [comment]
No, those failures were due to lock file issues.

**Pull request merged**
